"""inicial: crear tablas base

Revision ID: cf73a391b836
Revises: 
Create Date: 2025-09-21 18:15:51.330143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf73a391b836'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('socios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje_participacion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('operaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_operacion', sa.Enum('INGRESO', 'GASTO', 'RETIRO', 'DISTRIBUCION', name='tipooperacion'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moneda_original', sa.Enum('UYU', 'USD', name='moneda'), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('monto_uyu', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('localidad', sa.Enum('MONTEVIDEO', 'MERCEDES', name='localidad'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribuciones_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operacion_id', sa.UUID(), nullable=False),
    sa.Column('socio_id', sa.UUID(), nullable=False),
    sa.Column('monto_uyu', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operacion_id'], ['operaciones.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribuciones_detalle')
    op.drop_table('operaciones')
    op.drop_table('socios')
    op.drop_table('areas')
    # ### end Alembic commands ###
