"""add_verificaciones_ala_and_listas_metadata

Revision ID: e0b459903d90
Revises: h2i3j4k5l6m7
Create Date: 2026-02-03 18:20:13.073923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0b459903d90'
down_revision: Union[str, None] = 'h2i3j4k5l6m7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listas_ala_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre_lista', sa.String(length=50), nullable=False),
    sa.Column('url_fuente', sa.String(length=500), nullable=True),
    sa.Column('ultima_descarga', sa.DateTime(), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=True),
    sa.Column('cantidad_registros', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verificaciones_ala',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre_completo', sa.String(length=300), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('nacionalidad', sa.String(length=3), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('es_persona_juridica', sa.Boolean(), nullable=True),
    sa.Column('razon_social', sa.String(length=300), nullable=True),
    sa.Column('nivel_diligencia', sa.String(length=20), nullable=False),
    sa.Column('nivel_riesgo', sa.String(length=20), nullable=False),
    sa.Column('es_pep', sa.Boolean(), nullable=True),
    sa.Column('resultado_onu', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado_pep', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado_ofac', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado_ue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado_gafi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('busqueda_google_realizada', sa.Boolean(), nullable=True),
    sa.Column('busqueda_google_observaciones', sa.Text(), nullable=True),
    sa.Column('busqueda_news_realizada', sa.Boolean(), nullable=True),
    sa.Column('busqueda_news_observaciones', sa.Text(), nullable=True),
    sa.Column('busqueda_wikipedia_realizada', sa.Boolean(), nullable=True),
    sa.Column('busqueda_wikipedia_observaciones', sa.Text(), nullable=True),
    sa.Column('hash_verificacion', sa.String(length=64), nullable=False),
    sa.Column('certificado_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('expediente_id', sa.UUID(), nullable=True),
    sa.Column('contrato_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verificaciones_ala_contrato_id', 'verificaciones_ala', ['contrato_id'], unique=False)
    op.create_index('ix_verificaciones_ala_deleted_at', 'verificaciones_ala', ['deleted_at'], unique=False)
    op.create_index('ix_verificaciones_ala_expediente_id', 'verificaciones_ala', ['expediente_id'], unique=False)
    op.create_index('ix_verificaciones_ala_nivel_riesgo', 'verificaciones_ala', ['nivel_riesgo'], unique=False)
    op.create_index('ix_verificaciones_ala_nombre_completo', 'verificaciones_ala', ['nombre_completo'], unique=False)
    op.create_index('ix_verificaciones_ala_numero_documento', 'verificaciones_ala', ['numero_documento'], unique=False)
    op.create_index('ix_verificaciones_ala_usuario_id', 'verificaciones_ala', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verificaciones_ala_usuario_id', table_name='verificaciones_ala')
    op.drop_index('ix_verificaciones_ala_numero_documento', table_name='verificaciones_ala')
    op.drop_index('ix_verificaciones_ala_nombre_completo', table_name='verificaciones_ala')
    op.drop_index('ix_verificaciones_ala_nivel_riesgo', table_name='verificaciones_ala')
    op.drop_index('ix_verificaciones_ala_expediente_id', table_name='verificaciones_ala')
    op.drop_index('ix_verificaciones_ala_deleted_at', table_name='verificaciones_ala')
    op.drop_index('ix_verificaciones_ala_contrato_id', table_name='verificaciones_ala')
    op.drop_table('verificaciones_ala')
    op.drop_table('listas_ala_metadata')
    # ### end Alembic commands ###
